service: express-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  app:
    handler: index.handler  # This should match your export (module.exports.handler)
    events:
      - http:
          path: /
          method: get
      - http:
          path: /api/{proxy+}
          method: any
    environment:
      NODE_ENV: production

package:
  include:
    - node_modules/**
    - routes/**
    - index.js
